/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ProductosJpaController;
import Controlador.exceptions.NonexistentEntityException;
import Modelo.Productos;
import Modelo.Render;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class AdministrarProductos extends javax.swing.JInternalFrame {

    EntityManagerFactory emf;
    JDesktopPane jdesktop;
    ProductosJpaController productoJpa;


    public AdministrarProductos(EntityManagerFactory emf, JDesktopPane jdp) {

        this.emf = emf;
        this.jdesktop = jdesktop;
        productoJpa = new ProductosJpaController(emf);
        initComponents();
        CrearModelo();
        cargaInformacionProducto();
    }

    DefaultTableModel modelo;

    private void CrearModelo() {
        try {

            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "Id", "Nombre", "Decripcion", "Opciones", "Opciones"
                    }) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    javax.swing.JButton.class,
                    javax.swing.JButton.class

                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            jTableProductos.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
    }

    
    private void cargaInformacionProducto() {
        try {
            Object o[] = null;
            List<Productos> listaProductos = productoJpa.findProductosEntities();
            jTableProductos.setDefaultRenderer(Object.class, new Render());
            jTableProductos.setRowHeight(30);
            jButtonEditar.setName("editar");
            jbuttonEliminar.setName("eliminar");
            
            
            List<Productos> listaFinal = new ArrayList<>();
            Productos p;
            for (int i = 0; i < listaProductos.size(); i++) {
                if (listaProductos.get(i).getEstado().equalsIgnoreCase("A")) {
                    p = listaProductos.get(i);
                    listaFinal.add(p);
                }
            }

            for (int i = 0; i < listaFinal.size(); i++) {
                modelo.addRow(o);
                modelo.setValueAt(listaFinal.get(i).getIdProducto(), i, 0);
                modelo.setValueAt(listaFinal.get(i).getNombreProducto(), i, 1);
                modelo.setValueAt(listaFinal.get(i).getDescripcionProducto(), i, 2);
                modelo.setValueAt(jButtonEditar, i, 3);
                modelo.setValueAt(jbuttonEliminar, i, 4);
            }
             
          
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

        private AdministrarProductos() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jButtonAñadirProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        jButtonAñadirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/20183.png"))); // NOI18N
        jButtonAñadirProducto.setText("Añadir Producto");
        jButtonAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirProductoActionPerformed(evt);
            }
        });

        jLabel1.setText("Productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jButtonAñadirProducto))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButtonAñadirProducto)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonAñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirProductoActionPerformed

        RegistrarProductos a1 = new RegistrarProductos(emf);

        a1.setVisible(true);
        a1.setIconifiable(true);
        a1.setMaximizable(true);
        a1.setClosable(true);
        a1.setResizable(true);
        jdesktop.add(a1);
        dispose();
    }//GEN-LAST:event_jButtonAñadirProductoActionPerformed

    
    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked

        DefaultTableModel tm = (DefaultTableModel) jTableProductos.getModel();
        String dato = String.valueOf(tm.getValueAt(jTableProductos.getSelectedRow(), 0));
        Productos p = productoJpa.findProductos(Long.parseLong(dato));

        int column = jTableProductos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / jTableProductos.getRowHeight();

        if (row < jTableProductos.getRowCount() && row >= 0 && column < jTableProductos.getColumnCount() && column >= 0) {
            Object value = jTableProductos.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if (boton.getName().equalsIgnoreCase("editar")) {

                    EditarProducto a1 = new EditarProducto();
                    a1.setVisible(true);
                    a1.setIconifiable(true);
                    a1.setMaximizable(true);
                    a1.setClosable(true);
                    a1.setResizable(true);
                    jdesktop.add(a1);
                    dispose();
                } else {

                    int opc = JOptionPane.showConfirmDialog(null,
                            "Desea Eliminar el producto " + p.getNombreProducto(), "CONFIRMACIÓN", JOptionPane.YES_NO_OPTION);
                    if (opc == 0) {

                        try {
                            p.setEstado("B");
                            p.setDeletedAt(new Date());
                            productoJpa.edit(p);
                            CrearModelo();
                            cargaInformacionProducto();
                        } catch (NonexistentEntityException ex) {
                            Logger.getLogger(AdministrarProductos.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (Exception ex) {
                            Logger.getLogger(AdministrarProductos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                }
            }

        }


    }//GEN-LAST:event_jTableProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarProductos().setVisible(true);
            }
        });
    }
    JButton jButtonEditar = new JButton("Editar");

    JButton jbuttonEliminar = new JButton("Eliminar");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadirProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    // End of variables declaration//GEN-END:variables
}
