/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ArticulosJpaController;
import Controlador.ProductosJpaController;
import Controlador.exceptions.NonexistentEntityException;
import Modelo.Articulos;
import Modelo.Render;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class AdministraArticulos extends javax.swing.JInternalFrame {

    EntityManagerFactory emf;
    JDesktopPane jdesktop;
    ArticulosJpaController articuloJpa;
    ProductosJpaController productoJpa;


    public AdministraArticulos(EntityManagerFactory emf, JDesktopPane jdp) {
        
        this.emf = emf;
        this.jdesktop = jdp;
        articuloJpa = new ArticulosJpaController(emf);
        initComponents();
        CrearModelo();
        cargaInformacionArticulo();

    }

    DefaultTableModel modelo;

    private AdministraArticulos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void CrearModelo() {
        try {

            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "Id", "Producto", "Artículo", "Precio", "Stock", "Opciones", "Opciones"
                    }) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    javax.swing.JButton.class,
                    javax.swing.JButton.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            jTableArticulo.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
    }

    private void cargaInformacionArticulo() {
        try {
            Object o[] = null;
            List<Articulos> listaArticulos = articuloJpa.findArticulosEntities();
            jTableArticulo.setDefaultRenderer(Object.class, new Render());
            jTableArticulo.setRowHeight(30);
            jButtonEditar.setName("editar");
            jButtonEliminar.setName("eliminar");
            List<Articulos> listaFinal = new ArrayList<>();
            Articulos a;
            for (int i = 0; i < listaArticulos.size(); i++) {
                    listaFinal.add(listaArticulos.get(i));            
            }

            for (int i = 0; i < listaFinal.size(); i++) {
                modelo.addRow(o);
                modelo.setValueAt(listaFinal.get(i).getIdArticulo(), i, 0);
                modelo.setValueAt(listaFinal.get(i).getIdProducto().getNombreProducto(), i, 1);
                modelo.setValueAt(listaFinal.get(i).getNombreArticulo(), i, 2);
                modelo.setValueAt(listaFinal.get(i).getValorCompra(), i, 3);
                modelo.setValueAt(listaFinal.get(i).getStockArticulo(), i, 4);
                modelo.setValueAt(jButtonEditar, i, 5);
                modelo.setValueAt(jButtonEliminar, i, 6);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "Eoorro");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArticulo = new javax.swing.JTable();
        jButtonAñadirArticulo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArticuloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableArticulo);

        jButtonAñadirArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/20183.png"))); // NOI18N
        jButtonAñadirArticulo.setText("Añadir Artículo");
        jButtonAñadirArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirArticuloActionPerformed(evt);
            }
        });

        jLabel1.setText("Artículos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jButtonAñadirArticulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAñadirArticulo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArticuloMouseClicked

        DefaultTableModel tm = (DefaultTableModel) jTableArticulo.getModel();
        String dato = String.valueOf(tm.getValueAt(jTableArticulo.getSelectedRow(), 0));
        Articulos a = articuloJpa.findArticulos(Long.parseLong(dato));

        System.out.println(a);

        int column = jTableArticulo.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / jTableArticulo.getRowHeight();

        if (row < jTableArticulo.getRowCount() && row >= 0 && column < jTableArticulo.getColumnCount() && column >= 0) {
            Object value = jTableArticulo.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if (boton.getName().equalsIgnoreCase("editar")) {

                    EditarArticulos a1 = new EditarArticulos();
                    a1.setVisible(true);
                    a1.setIconifiable(true);
                    a1.setMaximizable(true);
                    a1.setClosable(true);
                    a1.setResizable(true);
                    jdesktop.add(a1);
                    dispose();
                } else {

                    int opc = JOptionPane.showConfirmDialog(null,
                            "Desea Eliminar el artículo " + a.getNombreArticulo(), "CONFIRMACIÓN", JOptionPane.YES_NO_OPTION);
                    if (opc == 0) {

                        try {
                            a.setEstado("B");
                            a.setDeletedAt(new Date());
                            articuloJpa.edit(a);
                            CrearModelo();
                            cargaInformacionArticulo();
                        } catch (NonexistentEntityException ex) {
                            Logger.getLogger(AdministrarProductos.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (Exception ex) {
                            Logger.getLogger(AdministrarProductos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                }
            }

        }

    }//GEN-LAST:event_jTableArticuloMouseClicked

    private void jButtonAñadirArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirArticuloActionPerformed

        RegistrarArticulos a1 = new RegistrarArticulos();

        a1.setVisible(true);
        a1.setIconifiable(true);
        a1.setMaximizable(true);
        a1.setClosable(true);
        a1.setResizable(true);

        jdesktop.add(a1);

        dispose();

    }//GEN-LAST:event_jButtonAñadirArticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministraArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministraArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministraArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministraArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministraArticulos().setVisible(true);
            }
        });
    }

    JButton jButtonEditar = new JButton("Editar");
    JButton jButtonEliminar = new JButton("Eliminar");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadirArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableArticulo;
    // End of variables declaration//GEN-END:variables
}
