/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.UsuariosistemaJpaController;

import Modelo.Roles;
import Modelo.Usuariosistema;
import Modelo.Usuariosistema_;
import java.awt.Dimension;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;

/**
 * @author carlos rubio
 */
public class VentanPrincipal extends javax.swing.JFrame {

    EntityManagerFactory emf;
    Roles rol;
    Usuariosistema usuario;
    UsuariosistemaJpaController usuarioJpa;

    public VentanPrincipal(EntityManagerFactory emf, Usuariosistema u) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setTitle("VENTANA PRINCIPAL CENTRO MÉDICO");
        this.usuario = u;
        this.emf = emf;
        usuarioJpa = new UsuariosistemaJpaController(emf);

        permisos();

    }

    public void permisos() {
        try {

            if (null != usuario.getIdRol().getNombreRol()) {
                switch (usuario.getIdRol().getNombreRol()) {
                    case "administrador":

                        break;
                    case "user":

                        break;
                    default:
                        break;
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemProdcutos = new javax.swing.JMenuItem();
        jMenuItemVerArticulos = new javax.swing.JMenuItem();
        jMenuProductos = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVerProductos = new javax.swing.JMenuItem();
        jMenuItemRegistrarArticulo = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemMpostrararea3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));

        jMenu1.setText("Ver");

        jMenuItemProdcutos.setText("Productos");
        jMenuItemProdcutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdcutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemProdcutos);

        jMenuItemVerArticulos.setText("Artículos");
        jMenuItemVerArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerArticulosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemVerArticulos);

        jMenuBar1.add(jMenu1);

        jMenuProductos.setText("Registrar");
        jMenuProductos.add(jSeparator1);

        jMenuItemVerProductos.setText("Productos");
        jMenuItemVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerProductosActionPerformed(evt);
            }
        });
        jMenuProductos.add(jMenuItemVerProductos);

        jMenuItemRegistrarArticulo.setText("Artículos");
        jMenuProductos.add(jMenuItemRegistrarArticulo);

        jMenuBar1.add(jMenuProductos);

        jMenuSalir.setText("Salir");

        jMenuItemMpostrararea3.setText("Cerrar Sesión");
        jMenuItemMpostrararea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMpostrararea3ActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemMpostrararea3);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMpostrararea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMpostrararea3ActionPerformed

        int opc = JOptionPane.showConfirmDialog(null,
                "Cerrar Sesión", "CONFIRMACIÓN", JOptionPane.YES_NO_OPTION);
        if (opc == 0) {
            Login l = new Login(emf);
            l.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_jMenuItemMpostrararea3ActionPerformed

    private void jMenuItemVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerProductosActionPerformed
        try {
            RegistrarProductos r1 = new RegistrarProductos(emf);
            r1.setVisible(true);
            r1.setIconifiable(true);
            r1.setMaximizable(true);
            r1.setClosable(true);
            r1.setResizable(true);
            jDesktopPane1.add(r1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemVerProductosActionPerformed

    private void jMenuItemProdcutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdcutosActionPerformed

        try {
            AdministrarProductos a1 = new AdministrarProductos(emf, jDesktopPane1);
            a1.setVisible(true);
            a1.setIconifiable(true);
            a1.setMaximizable(true);
            a1.setClosable(true);
            a1.setResizable(true);
            jDesktopPane1.add(a1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jMenuItemProdcutosActionPerformed

    private void jMenuItemVerArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerArticulosActionPerformed
        try {
            AdministraArticulos a1 = new AdministraArticulos(emf, jDesktopPane1);
            a1.setVisible(true);
            a1.setIconifiable(true);
            a1.setMaximizable(true);
            a1.setClosable(true);
            a1.setResizable(true);
            jDesktopPane1.add(a1);

        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemVerArticulosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemMpostrararea3;
    private javax.swing.JMenuItem jMenuItemProdcutos;
    private javax.swing.JMenuItem jMenuItemRegistrarArticulo;
    private javax.swing.JMenuItem jMenuItemVerArticulos;
    private javax.swing.JMenuItem jMenuItemVerProductos;
    private javax.swing.JMenu jMenuProductos;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
